### ISSUE TITLE
Generating IUPAC names from markush structures makes the app crash

### ISSUE THREAD

**Issue by OBrink** [OBrink/DECIMER_Web#48]
another follow-up due to DECIMER's ability to read markush structures

from the Docker logs:

```
Traceback (most recent call last):
  File "/var/www/app/public/../app/Python/get_smiles_from_mol_blocks.py", line 45, in <module>
    main()
  File "/var/www/app/public/../app/Python/get_smiles_from_mol_blocks.py", line 31, in main
    mol_block_arr = decode_mol_block_array(sys.argv[1])
  File "/var/www/app/public/../app/Python/get_smiles_from_mol_blocks.py", line 22, in decode_mol_block_array
    mol_block_arr = eval(str_mol_block_arr)
  File "<string>", line 1
SyntaxError: unexpected character after line continuation character
```

- I would just avoid trying to do that altogether

**Comment by OBrink** [comment]
It does not crash anymore, but the R groups are lost when the IUPAC names are generated
